minimum_allowable_node_id: 1
maximum_allowable_node_id: 5000
minimum_allowable_link_id: 1
maximum_allowable_link_id: 1000
nodes_used_by_geography:
  - geography_name: All
    start: 0
    end: 1000
  - geography_name: Dummy
    start: 2000
    end: 2000
links_used_by_geography:
  - geography_name: All
    start: 0
    end: 500
  - geography_name: Dummy
    start: 700
    end: 700
