minimum_allowable_node_id: 1
maximum_allowable_node_id: 5500000
minimum_allowable_link_id: 1
maximum_allowable_link_id: 9000000
nodes_used_by_geography:
  - geography_name: San Francisco TAZ
    start: 1
    end: 9999
  - geography_name: San Francisco MAZ
    start: 10000
    end: 89999
  - geography_name: San Francisco TAP
    start: 90000
    end: 99999
  - geography_name: San Mateo TAZ
    start: 100000
    end: 109999
  - geography_name: San Mateo MAZ
    start: 110000
    end: 189999
  - geography_name: San Mateo TAP
    start: 190000
    end: 199999
  - geography_name: Santa Clara TAZ
    start: 200000
    end: 209999
  - geography_name: Santa Clara MAZ
    start: 210000
    end: 289999
  - geography_name: Santa Clara TAP
    start: 290000
    end: 299999
  - geography_name: Alameda TAZ
    start: 300000
    end: 309999
  - geography_name: Alameda MAZ
    start: 310000
    end: 389999
  - geography_name: Alameda TAP
    start: 390000
    end: 399999
  - geography_name: Contra Costa TAZ
    start: 400000
    end: 409999
  - geography_name: Contra Costa MAZ
    start: 410000
    end: 489999
  - geography_name: Contra Costa TAP
    start: 490000
    end: 499999
  - geography_name: Solano TAZ
    start: 500001
    end: 509999
  - geography_name: Solano MAZ
    start: 510000
    end: 589999
  - geography_name: Solano TAP
    start: 590000
    end: 599999
  - geography_name: Napa TAZ
    start: 600000
    end: 609999
  - geography_name: Napa MAZ
    start: 610000
    end: 689999
  - geography_name: Napa TAP
    start: 690000
    end: 699999
  - geography_name: Sonoma TAZ
    start: 700000
    end: 709999
  - geography_name: Sonoma MAZ
    start: 710000
    end: 789999
  - geography_name: Sonoma TAP
    start: 790000
    end: 799999
  - geography_name: Marin TAZ
    start: 800000
    end: 804999
  - geography_name: Marin MAZ
    start: 805000
    end: 844999
  - geography_name: Marin TAP
    start: 845000
    end: 849999
  - geography_name: San Joaquin TAZ
    start: 850000
    end: 854999
  - geography_name: San Joaquin MAZ
    start: 855000
    end: 894999
  - geography_name: San Joaquin TAP
    start: 895000
    end: 899999
  - geography_name: External TAZ
    start: 900000
    end: 999999
  - geography_name: San Francisco Network
    start: 1000000
    end: 1028040
  - geography_name: San Mateo Network
    start: 1500000
    end: 1556391
  - geography_name: Santa Clara Network
    start: 2000000
    end: 2192948
  - geography_name: Alameda Network
    start: 2500000
    end: 2700000
  - geography_name: Contra Costa Network
    start: 3000000
    end: 3097286
  - geography_name: Solano Network
    start: 3500000
    end: 3547320
  - geography_name: Napa Network
    start: 4000000
    end: 4013832
  - geography_name: Sonoma Network
    start: 4500000
    end: 4556145
  - geography_name: Marin Network
    start: 5000000
    end: 5030001
  - geography_name: San Joaquin Network
    start: 5150000
    end: 5300000
  - geography_name: External Network
    start: 5300000
    end: 5500000
links_used_by_geography:
  - geography_name: San Francisco
    start: 1
    end: 127974
  - geography_name: San Mateo
    start: 1000000
    end: 1200489
  - geography_name: Santa Clara
    start: 2000000
    end: 2652149
  - geography_name: Alameda
    start: 3000000
    end: 3434585
  - geography_name: Contra Costa
    start: 4000000
    end: 4322027
  - geography_name: Solano
    start: 5000000
    end: 5155993
  - geography_name: Napa
    start: 6000000
    end: 6046605
  - geography_name: Sonoma
    start: 7000000
    end: 7176047
  - geography_name: Marin
    start: 8000000
    end: 8083415
  - geography_name: San Joaquin
    start: 8500000
    end: 9000000
