name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          pip install --user -e git+https://github.com/wsp-sag/network_wrangler.git@master#egg=network_wrangler
          pytest -s -m ci
